/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.registerswing.view;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.beans.PropertyVetoException;
import javax.swing.BorderFactory;
import javax.swing.JInternalFrame;

/**
 * @author Diego Barbosa da Silva
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        cadastroProduto = new javax.swing.JMenuItem();
        cadastroCliente = new javax.swing.JMenuItem();
        cadastroUsuario = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        estoqueAtual = new javax.swing.JMenuItem();
        estoqueHistorico = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );

        menuCadastro.setMnemonic('f');
        menuCadastro.setText("Cadastro");

        cadastroProduto.setMnemonic('o');
        cadastroProduto.setText("Produto");
        cadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroProdutoActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroProduto);

        cadastroCliente.setMnemonic('s');
        cadastroCliente.setText("Cliente");
        menuCadastro.add(cadastroCliente);

        cadastroUsuario.setMnemonic('a');
        cadastroUsuario.setText("Usuário");
        menuCadastro.add(cadastroUsuario);

        barraMenu.add(menuCadastro);

        menuEstoque.setMnemonic('e');
        menuEstoque.setText("Estoque");

        estoqueAtual.setMnemonic('t');
        estoqueAtual.setText("Estoque Atual");
        menuEstoque.add(estoqueAtual);

        estoqueHistorico.setMnemonic('y');
        estoqueHistorico.setText("Histórico");
        menuEstoque.add(estoqueHistorico);

        barraMenu.add(menuEstoque);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Venda");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        barraMenu.add(helpMenu);

        jMenu1.setText("Relatórios");
        barraMenu.add(jMenu1);

        jMenu2.setText("Opções");
        barraMenu.add(jMenu2);

        jMenu3.setText("Sobre");
        barraMenu.add(jMenu3);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroProdutoActionPerformed
        TelaProdutoView produtoView = new TelaProdutoView();
        configureFrame(produtoView);
        desktop.add(produtoView).setVisible(true);
    }//GEN-LAST:event_cadastroProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /**
         * Configura o tema FlatLaf
         */
        FlatIntelliJLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    private void configureFrame(JInternalFrame frame) {
        try {
            frame.setClosable(true);
            frame.setMaximizable(true);
            frame.setResizable(true);
            frame.setIconifiable(true);

            // Configurações específicas do FlatLaf
            frame.putClientProperty("JInternalFrame.frameType", "optionDialog");
            frame.setFrameIcon(null);

            frame.setMaximum(true);
        } catch (PropertyVetoException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem cadastroCliente;
    private javax.swing.JMenuItem cadastroProduto;
    private javax.swing.JMenuItem cadastroUsuario;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem estoqueAtual;
    private javax.swing.JMenuItem estoqueHistorico;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuEstoque;
    // End of variables declaration//GEN-END:variables

}
