package com.registerswing.view;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import com.registerswing.view.janela.JanelaSobreInfoView;
import java.awt.EventQueue;
import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;

/**
 * @author Diego Barbosa da Silva
 */
public class MenuView extends javax.swing.JFrame {

    private boolean darkMode = false;

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        cadastroCliente = new javax.swing.JMenuItem();
        cadastroProduto = new javax.swing.JMenuItem();
        cadastroUsuario = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        estoqueAtual = new javax.swing.JMenuItem();
        estoqueHistorico = new javax.swing.JMenuItem();
        menuVenda = new javax.swing.JMenu();
        pedidoVenda = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menuOpcoes = new javax.swing.JMenu();
        modoEscuro = new javax.swing.JCheckBoxMenuItem();
        menuSobre = new javax.swing.JMenu();
        menuInformacoes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );

        barraMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuCadastro.setMnemonic('f');
        menuCadastro.setText("Cadastro");
        menuCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cadastroCliente.setMnemonic('s');
        cadastroCliente.setText("Cliente");
        cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroCliente);

        cadastroProduto.setMnemonic('o');
        cadastroProduto.setText("Produto");
        cadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroProdutoActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroProduto);

        cadastroUsuario.setMnemonic('a');
        cadastroUsuario.setText("Usuário");
        cadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroUsuarioActionPerformed(evt);
            }
        });
        menuCadastro.add(cadastroUsuario);

        barraMenu.add(menuCadastro);

        menuEstoque.setMnemonic('e');
        menuEstoque.setText("Estoque");
        menuEstoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        estoqueAtual.setMnemonic('t');
        estoqueAtual.setText("Estoque Atual");
        estoqueAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueAtualActionPerformed(evt);
            }
        });
        menuEstoque.add(estoqueAtual);

        estoqueHistorico.setMnemonic('y');
        estoqueHistorico.setText("Histórico");
        menuEstoque.add(estoqueHistorico);

        barraMenu.add(menuEstoque);

        menuVenda.setMnemonic('h');
        menuVenda.setText("Venda");
        menuVenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        pedidoVenda.setMnemonic('c');
        pedidoVenda.setText("Pedidos");
        pedidoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoVendaActionPerformed(evt);
            }
        });
        menuVenda.add(pedidoVenda);

        barraMenu.add(menuVenda);

        menuRelatorio.setText("Relatórios");
        menuRelatorio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        barraMenu.add(menuRelatorio);

        menuOpcoes.setText("Opções");
        menuOpcoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        modoEscuro.setText("Modo Escuro");
        modoEscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoEscuroActionPerformed(evt);
            }
        });
        menuOpcoes.add(modoEscuro);

        barraMenu.add(menuOpcoes);

        menuSobre.setText("Sobre");
        menuSobre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuInformacoes.setText("Informações");
        menuInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInformacoesActionPerformed(evt);
            }
        });
        menuSobre.add(menuInformacoes);

        barraMenu.add(menuSobre);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroProdutoActionPerformed
        TelaProdutoView produtoView = new TelaProdutoView();
        configureFrame(produtoView);
        desktop.add(produtoView).setVisible(true);
    }//GEN-LAST:event_cadastroProdutoActionPerformed

    private void cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroClienteActionPerformed
        TelaClienteView clienteView = new TelaClienteView();
        configureFrame(clienteView);
        desktop.add(clienteView).setVisible(true);
    }//GEN-LAST:event_cadastroClienteActionPerformed

    private void modoEscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoEscuroActionPerformed
        if (modoEscuro.isSelected()) {
            EventQueue.invokeLater(() -> {
                FlatAnimatedLafChange.showSnapshot();
                FlatDarculaLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
            });
        } else {
            EventQueue.invokeLater(() -> {
                FlatAnimatedLafChange.showSnapshot();
                FlatIntelliJLaf.setup();
                FlatLaf.updateUI();
                FlatAnimatedLafChange.hideSnapshotWithAnimation();
            });
        }
    }//GEN-LAST:event_modoEscuroActionPerformed

    private void cadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroUsuarioActionPerformed
        TelaUsuarioView usuarioView = new TelaUsuarioView();
        configureFrame(usuarioView);
        desktop.add(usuarioView).setVisible(true);
    }//GEN-LAST:event_cadastroUsuarioActionPerformed

    private void estoqueAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueAtualActionPerformed
        TelaEstoqueView estoqueView = new TelaEstoqueView();
        configureFrame(estoqueView);
        desktop.add(estoqueView).setVisible(true);
    }//GEN-LAST:event_estoqueAtualActionPerformed

    private void pedidoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoVendaActionPerformed
        TelaPedidoView pedidoView = new TelaPedidoView();
        configureFrame(pedidoView);
        desktop.add(pedidoView).setVisible(true);
    }//GEN-LAST:event_pedidoVendaActionPerformed

    private void menuInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInformacoesActionPerformed
        JanelaSobreInfoView janelaSobreInfoView = new JanelaSobreInfoView(this, true);
        janelaSobreInfoView.setTitle("Informações");
        janelaSobreInfoView.setVisible(true);
    }//GEN-LAST:event_menuInformacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /**
         * Configura o tema FlatLaf
         */
        FlatIntelliJLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    private void configureFrame(JInternalFrame frame) {
        try {
            frame.setClosable(true);
            frame.setMaximizable(true);
            frame.setResizable(true);
            frame.setIconifiable(true);
            // Configurações específicas do FlatLaf
            frame.putClientProperty("JInternalFrame.frameType", "optionDialog");
            frame.setFrameIcon(null);
            frame.setMaximum(true);
        } catch (PropertyVetoException e) {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem cadastroCliente;
    private javax.swing.JMenuItem cadastroProduto;
    private javax.swing.JMenuItem cadastroUsuario;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem estoqueAtual;
    private javax.swing.JMenuItem estoqueHistorico;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenuItem menuInformacoes;
    private javax.swing.JMenu menuOpcoes;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JMenu menuVenda;
    private javax.swing.JCheckBoxMenuItem modoEscuro;
    private javax.swing.JMenuItem pedidoVenda;
    // End of variables declaration//GEN-END:variables

}
